[versions]
agp = "8.6.1"
kotlin = "1.9.24"
reactNativeGradlePlugin = "0.82.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library     = { id = "com.android.library",     version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
react-native        = { id = "com.facebook.react",          version.ref = "reactNativeGradlePlugin" }
react-settings      = { id = "com.facebook.react.settings", version.ref = "reactNativeGradlePlugin" }
